### ISSUE TITLE
OpenMetaOffice-Flutter在Linux上编译通过，在MacOS上报错

### ISSUE THREAD

**Issue by taotao2008** [OpenIMSDK/OpenMetaOffice-Flutter#1]
版本信息：
OS：macOS Big Sur 11.6
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (7 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
错误信息：
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/10294984/144800185-db9010d3-d5f7-4baa-ba1f-ec6cd54ca8e5.png">

OpenMetaOffice-Flutter % flutter run -d R5CNC04N76R
Launching lib/main.dart on SM N9860 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
../../../../../.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/decimal-2.0.0/lib/decimal.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
    return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
                                                          ^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:134:29: Error: A value of type 'Rational' can't be returned from a function with return type 'Decimal'.
 - 'Rational' is from 'package:rational/rational.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/rational-2.0.0/lib/rational.dart').
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/decimal-2.0.0/lib/decimal.dart').
    return Decimal.parse(a) / Decimal.parse(b);
                            ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/huangjuntao/worker/Packages/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/huangjuntao/worker/Packages/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Running Gradle task 'assembleDebug'...                             20.5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hrxiang** [comment]
dependency_overrides:
  decimal: 1.5.0

**Comment by taotao2008** [comment]
@hrxiang thanks, resolve it
